#SPDX-License-Identifier: MIT-0
---
- name: Install Kitty
  package:
    name:   kitty
    state:  present

- name: Link config
  file:
    state:  link
    src:    "{{ role_path }}/files/config/"
    dest:    ~/.config/kitty
